### ISSUE TITLE
Provide an option to force a gem version, even it it conflicts with a gem's declared compatibility.

### ISSUE THREAD

**Issue by xaviershay** [bundler/bundler-features#20]
From https://github.com/bundler/bundler/issues/2412

Still debate about how this would be done or whether it's a good idea. See linked ticket for context.

**Comment by endymion** [comment]
I respectfully add my vote to this feature request.  Bundler's lack of a feature for forcing a version that's known to work has cost me hours of extra work today.  It's an even bigger issue when you're dealing with older Ruby code that uses Gems where the authors have locked the dependencies to something like "~> 1.2.5" and then stopped maintaining a gem.  Sometimes a gem doesn't really need to be updated because it works, but it's still full of over-specific dependencies like that.  The only way to deal with it right now is to fork the gem itself and update the dependencies.  Bundler could easily have made my life a lot simpler today by giving me more flexibility and control and letting me take responsibility for my own QA.

**Comment by indirect** [comment]
@endymion Thanks for the feedback. Today, no one on the Bundler core team has the time to do the work that this feature would involve. If someone joins the team who wants to implement and support the feature, or [Ruby Together](https://rubytogether) is willing to fund work on this feature, we'll take another look.

**Comment by thewoolleyman** [comment]
@indirect I do agree with your previous comments that this could make the situation worse for Gem maintainers, because they don't know if a bug report is due to an incompatible overridden dependency version being used.

I still think the long-term solution is to encourage/force people to use pessimistic constraints correct.  E.g., docs on rubygems.org, and rubygems itself should complain loudly if you try to put a dependency version in a gemspec with a three-component pessimistic constraint, because in all likelihood You're Doing It Wrong.

Maybe someone (with more time and who cares more than me) can open that discussion on the RubyGems mailing list along these lines (and cross-link it here in a comment), and see what comes of that...

-- Chad

**Comment by indirect** [comment]
The RubyGems.org pages have all changed to default to `~> X.Y` version constraints available for copying. I think it _might_ be worth it to warn if a gemspec has a pessimistic constraint on a bugfix release, but unfortunately there are many, many, many, gems that only function correctly at a precise bugfix release. :( It's a chicken and egg problem that I'm not sure how to progress on.

**Comment by jfinkhaeuser** [comment]
If a gem has a constraint on a specific bugfix release because that's the only version it works with, that's a bug in the dependency.

Or, to go by example:
- Gem A exists in version 0.1.1
- Gem B requires precisely version 0.1.1, because it doesn't work with version 0.1.0

Then Gem A uses semantic versioning wrong. That cannot be emphasised enough.

The point of semantic versioning is to provide a stable interface across all releases with the same major and minor component. A bugfix that breaks the interface is simply no longer compatible with the same major and minor component.

Penalizing Gem B for doing the only thing left for it to do seems like entirely the wrong approach.

Gem B should specify dependencies as `~0.1 >=0.1.1` in this case. Being helpful about this would IMHO be a good feature.

But really, it's the Gem A maintainers that need to be given a hard time, not anyone else.

(Mind you, there is no easy solution to this. The best solution so far is to differentiate between interface and package versions, and depend on an interface version. That's happening to a degree in Linux/Solaris shared object libraries, and vastly improves some issues, but it's not bullet proof either.)

**Comment by booleanbetrayal** [comment]
would definitely find this feature useful!

**Comment by xeger** [comment]
I deal with a lot of abandonware gems whose authors never learned to manage dependencies correctly. I get bit by falsely-rigid constraints several times per year, preventing me from fixing security or functional defects in my _own_ software. I solve these by forking the offending gem and fixing the constraint.

Once in a very great while I find that there was a genuine reason for the author to be so pedantic. Generally, however, they were just ignorant about the pessimistic versioning notation. I fix the constraints, open a futile pull request in case the author ever wakes up again, and add a tech-debt item to stop depending on the offending gem.

Needless to say, I would find this feature _very_ helpful. That having been said, there's almost always a workaround -- forking the gem and depending on it as gitted, or pulling from a custom source -- so I understand the core team's unwillingness to spend precious cycles on the feature.

Nevertheless, I'd love to see a feature like this emerge! It would save me significant time in the long run. So, err, +1, and perhaps I'll spend some time implementing it, if I become seriously blocked.

**Comment by todd-richmond** [comment]
very well put - thx! That is the exact issue we had... small, but highly useful gems that have been abandoned by their author with restrictions they didn't fully understand before going dark. In this case forking is a pain because we have to manage them and if the author ever does make changes, we probably won't notice

This is somewhat similar to maven's ability to exclude package dependencies so that you can enable the use of newer packages. The developer is owning the conflicts at that point so a warning would be fine, but far better than having to fork and hack

**Comment by vbabu75** [comment]
+1

**Comment by jirihradil** [comment]
+1

**Comment by RochesterinNYC** [comment]
I'm interested in working on this if it's still something the Bundle maintainers want to trend towards/support.

**Comment by teadur** [comment]
+1

**Comment by Maxim-Gurin** [comment]
+1

**Comment by egormasalitin** [comment]
+1

**Comment by anton-fedorov** [comment]
+1

**Comment by oleksandr-oksenenko** [comment]
+1

**Comment by yuliiakorzhuk** [comment]
+1

**Comment by batytskyy** [comment]
+1

**Comment by asukhorukova** [comment]
+1

**Comment by andreiiarnautov** [comment]
+1

**Comment by a-paschenko** [comment]
+1

**Comment by spopkov** [comment]
+1

**Comment by eugeneugrevatov** [comment]
+1

**Comment by eugene-ivakhno** [comment]
+1

**Comment by OlegKlymenko** [comment]
+1

**Comment by segiddins** [comment]
This deluge of `:+1:`s is unhelpful -- please add a :+1: reaction to the original post.

**Comment by yuri-taran** [comment]
+1

**Comment by vstepchik** [comment]
+1

**Comment by LynnCo** [comment]
Moved to https://github.com/bundler/bundler/issues/4552
