### ISSUE TITLE
Automatically figure out optimum processes to parallelize on

### ISSUE THREAD

**Issue by arnab** [bundler/bundler-features#44]
Right now, bundler allows users to specify number of processes to use with a `--jobs n` option (for `install` and `update`). Instead of having the user figure out the optimal number, I propose:

+ add a `--parallel`option: which will automatically default to `n-1` jobs.
+ if `--jobs n` option is provided, the user's preferred number (`n`) will override the optimum calculation.

If this sounds like a good idea, I would love to work on it.

Related: is there a reason, we don't default to run parallelly (with a optional `--no-parallel`)?

**Comment by olivierlacan** [comment]
As @sikachu showed two years ago in https://robots.thoughtbot.com/parallel-gem-installing-using-bundler, it's possible (at least on OS X) to determine the number of logical cores on an OS X machines and by using the following we can give a great default experience for people on multi-core machines:

```
number_of_cores=`sysctl -n hw.ncpu`
bundle config --global jobs `expr $number_of_cores - 1`
```

I'll admit I don't know if this is at all portable but at the very least this setting could be set if the command answers and not set otherwise. 

Every time I set up bundler on a new machine I find myself wondering how `bundle install` is so slow. This is something that would especially affect beginners and people who are not familiar with bundler configuration.

**Comment by fotanus** [comment]
On GNU core that is a handy program. That would be `number_of_cores=$(nproc) `.

**Comment by LynnCo** [comment]
Closing in favor of https://github.com/bundler/bundler/issues/4504, please continue discussion there!
