### ISSUE TITLE
bundle install --only

### ISSUE THREAD

**Issue by rymohr** [bundler/bundler-features#59]
Proposing the addition of `bundle install --only group1 group2` as the whitelist counterpart to `bundle install --without`.  When you grow out of the basic rails environments it's much easier to express the desired gems as a whitelist.

```
bundle install --only default production
```

This prevents the addition of new groups from breaking previous builds too.

**Comment by SleeplessByte** [comment]
:+1:

**Comment by wiggly** [comment]
+1

**Comment by jhass** [comment]
https://github.com/bundler/bundler/issues/3531 was accepted and I think it covers most, if not all usecases described here, so I think we can close this.

**Comment by MOZGIII** [comment]
If someone is still searching for it: https://github.com/MOZGIII/bundle-only
Could probably still be merged into the bundler project itself.

Yes, I know `--with` and optional groups exist.

**Comment by will-in-wi** [comment]
I'll throw out another use case for `--only` where the existing features aren't helpful.

I have a deployment CI server which only needs Capistrano to be downloaded. Rather than downloading all of the gems that a project requires, I've put the Capistrano gems into a `:deployment` group which is excluded from the production install. On the CI server, I presently need to run `--without="default test development common_dev stage production"` and it is highly likely that if another group is ever added, the committer will forget to put that group in the CI config file. Being able to write `--only="deployment"` would be ideal.

Thanks!

**Comment by will-in-wi** [comment]
If anyone who has previously lobbied for this feature still needs it, please comment with your use case on https://github.com/bundler/bundler/pull/4907. I've made a PR, and I'm trying to convince the maintainers that it is worth it. Thanks!

@rymohr, @colinrymer, @geksilla, @s74, @harto, @MrMMorris, @evgeny-goldin, @donbobka, @agavrik, @prashantrajan, @MarioLinden, @ma2gedev, @SleeplessByte, @wiggly
