### ISSUE TITLE
bundle install --with aka optional groups

### ISSUE THREAD

**Issue by jhass** [bundler/bundler-features#68]
This is a competing proposal to #59, https://github.com/bundler/bundler/issues/1636.

I think most command line semantic issues can be solved by supporting optional groups. These would be declared in the `Gemfile` as follows:

```ruby
group :mysql, optional: true do
  gem 'mysql2'
end

group :postgresql, optional: true do
  gem 'pg'
end
```

With this Gemfile, a plain `bundle install` would install nothing. `bundle install --with mysql` would install MySQL support, `bundle install --with mysql postgresql` would install both.

Like `--without`, `--with` is a remembered option. Running `bundle install --without mysql` is allowed but has no effect. Running `bundle install --with mysql` followed by a `bundle install --without mysql` will remove the group from the list of remembered to install groups. Running `bundle install --without development` followed by a `bundle install --with development` will remove the group from the list of remembered to not install groups. Running `bundle install --with mysql --without mysql` will throw an error. Passed arguments to either option will be merged to the list of remembered arguments.

The example is chosen to show a potential benefit of this feature: When distributing a software with for example support for multiple database backends, the installation instructions can instruct to do `bundle install --with mysql` to get MySQL support, `bundle install --with postgresql` to get PostgreSQL. Currently one has to instruct to run `bundle install --without postgresql` to get MySQL support and `bundle install --without mysql` to get PostgreSQL. This is very confusing and gets worse if you support a third possibility. I've seen workarounds to this issue by making the line in the Gemfile conditional based on environment variables or reading a configuration file. Both make the lock dirty and effectively harm the adoption of the `--deployment` flag on production.

**Comment by steakknife** [comment]
Perhaps:

Just encountered this use-case again, so here's my 20 millicents.

Another possible solution for conditionals to support `bundle package --all` could be:

```ruby
group :db_sqlite, condition: -> { driver? 'sqlite' } do
  gem 'sqlite3'
end

group :db_postgres, condition: -> { driver? 'postgres' } do
  gem 'pg'
end

# or simply

condition: -> { driver? 'postgres' } do
  gem 'pg'
end

# one-off

gem 'rails_12factor', condition: -> { ENV.keys.grep(/HEROKU/).any? }
```

Such that the lambda is evaluated sometime *after* Bundler is completely loaded, and the block happens if the lambda returns truthy (so inside the lambda might be your own DSL: `driver?` for example).

And then somehow augment Gemfile.lock to include a bit of ruby (the contents of the lambda) (Yea security or functionality, pick 1.5) 

That way, prod, dev, whatever will run idempotently and as expected, and also arbitrary expressions can be used without breaking `package --all`.  This makes bundler sufficiently general without going *too crazy*, just a little batters with ruby in the yaml.

Per https://github.com/bundler/bundler/issues/1636

**Comment by jhass** [comment]
Implemented by https://github.com/bundler/bundler/issues/3531

**Comment by steakknife** [comment]
¡Gracias! :beers:
Mahalo
