### ISSUE TITLE
(optionally) don't put SHA in directory name of vendored source folders

### ISSUE THREAD

**Issue by eapache** [bundler/bundler-features#76]
When `package --all` places unpacked source code into `vendor/cache` (for example when the source of the gem is a git SHA instead of ruby-gems) the generated folder name contains the SHA.

We fully vendor our gems (commit `vendor/cache` to git) for legal compliance reasons, and the fact that the generated directory names include the SHA makes it rather painful to upgrade such gems, since the diff ends up full of useless renames.

It would be very helpful if bundler (either by default, or with a flag) would not include the SHA in the directory name.

**Comment by indirect** [comment]
So, if I'm understanding correctly, you are checking in the contents of your `vendor/cache` directory, including git gems, and your complaint is that the `git diff` command shows many file renames? Have you considered building `.gem` files out of your git gems that you can check into vendor/cache instead?

In general, this change is not okay, and breaks everything about how `vendor/cache` works. It's the same as asking us to remove the version numbers from the `.gem` files in `vendor/cache`. The reason we include version numbers is because `rack-1.0.0.gem` is a completely different gem than `rack-1.0.1.gem`. This feature would effectively reduce all instances to `rack.gem`, making it impossible for Bundler to tell which version of each gem was cached.

If the git diff bothers you, I reccomend putting the contents of your `vendor/cache` directory into another git repository, and linking it to your main repository via submodules. Then git can guarantee you are using the exact code you expect, but the diffs aren't part of the repository you actively work in.

**Comment by eapache** [comment]
> Have you considered building .gem files out of your git gems that you can check into vendor/cache instead?

They have to be vendored as source for legal reasons.

> making it impossible for Bundler to tell which version of each gem was cached.

Ah. The version (or SHA, or ...) could be stored elsewhere though, couldn't it? For example [GoDep](https://github.com/tools/godep) (a similar tool for Golang which we use in the same situation) stores the SHAs in a separate file (a la Gemfile.lock) and stores the actual source in a consistent directory. Does this sound like a reasonable compromise?

> linking it to your main repository via submodules

Because [`git replace`](http://git-scm.com/docs/git-replace) permits amending SHAs without changing their ref, submodules unfortunately do not fulfil our legal requirements around source code integrity.

---

(I do realize that our situation is unique and rather bizarre due to legal restrictions, but given that GoDep works for us, I don't think it's totally impossible to make bundler work as well)

**Comment by indirect** [comment]
Based on what you're describing, Bundler already supports what you want. Copy the files of the gem into a directory, check them in, and use the `:path` option in your Gemfile.

(Incidentally, the `git replace` documentation points out that you can simply set `GIT_NO_REPLACE_OBJECTS` to prevent `git replace` changes from having any affect, so I'm not sure why that matters)

**Comment by eapache** [comment]
> Copy the files of the gem into a directory, check them in, and use the :path option in your Gemfile.

We've written a script to do that and to store the SHA in `.revision` file at the root, but we were hoping that there was some easy way to have bundler handle the handle the whole thing :)

> so I'm not sure why that matters

lawyers :/
