### ISSUE TITLE
Parsing the output of `outdated`

### ISSUE THREAD

**Issue by jaredbeck** [bundler/bundler-features#85]
### Current output of `bundle outdated`

```
Updating git://github.com/airblade/paper_trail.git
Fetching gem metadata from https://rails-assets.org/..
Fetching version metadata from https://rails-assets.org/.
Fetching gem metadata from http://rubygems.org/..............
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Resolving dependencies......

Outdated gems included in the bundle:
  * newrelic_rpm (3.12.0.288 > 3.11.2.286)
  * rack (1.6.1 > 1.6.0)
  * scrypt (2.0.0 > 1.2.1)
  * slop (4.1.0 > 3.6.0)
  * sprockets-rails (2.3.0 > 2.2.4)
  * tilt (2.0.1 > 1.4.1)
```

### Desired output of `bundle outdated --quiet`

```
newrelic_rpm (3.12.0.288 > 3.11.2.286)
rack (1.6.1 > 1.6.0)
scrypt (2.0.0 > 1.2.1)
slop (4.1.0 > 3.6.0)
sprockets-rails (2.3.0 > 2.2.4)
tilt (2.0.1 > 1.4.1)
```

### Why?

The goal is to have minimal, predictable output that scripts can consume.  Interested?  I'd be happy to help implement.

**Comment by simi** [comment]
It will be fine to make --quite globally for all commands with one implementation.

**Comment by indirect** [comment]
The existing --quiet option suppresses all output, so I don't think that's a good fit here. Rather than a `--quiet` option, how about only printing the minimal list when output is being piped or redirected?

**Comment by jaredbeck** [comment]
> The existing --quiet option suppresses all output, so I don't think that's a good fit here. 

When I run `bundle outdated --quiet` (1.9.6) I get `Unknown switches '--quiet'`.  So, are you saying you would want `outdated --quiet`, *if ever implemented*, to operate the same as existing commands that *do* support `--quiet`?  That would make sense.

> Rather than a --quiet option, how about only printing the minimal list when output is being piped or redirected?

That would work.  It seems like the feature would be less "discoverable", and harder to document, but it's not an uncommon idea.  `ls`, for example uses a different delimiter when piped (newlines).

Alternatively, we could think up a different name for the option, other than `--quiet`.  I'm not sure where to look for inspiration.  The only thing that comes to mind is `git status --porcelain`.

```
       --porcelain
           Give the output in an easy-to-parse format for scripts. This is similar to the
           short output, but will remain stable across Git versions and regardless of user
           configuration. See below for details.
```

There's a weird option name, no?

**Comment by RochesterinNYC** [comment]
Hm, I like the different output when piped idea, but it also feels a bit unexpected user/developer-wise. 

Say I was a developer using bundler and was trying to use the output format of `bundle outdated` for ingestion by some personal script or library. I would probably use regular `bundle outdated`, look at the format of the output, and then try to write code or use something to parse the output I see properly. Then, my code starts erroring out or misbehaving when I use it on a piped `bundle outdated`. I'm confused, I debug, and then eventually I find out that the `bundle outdated` piped output is in a different format.

UX-wise, that doesn't sound stellar. However, with stellar documentation and possibly an initial influx of issues or StackOverflow questions, different format when piped behavior might become more common knowledge in the bundler ecosystem? I could also see it potentially breaking some people's existing code to parse `bundle outdated` though.

Though overall, I think adding/implementing a flag like `--porcelain` for `git status` (maybe `--minimal` or something?) is a better developer UX.

**Comment by jaredbeck** [comment]
>>>    Rather than a --quiet option, how about only printing the minimal list when output is being piped or redirected?
>>
>> That would work. It seems like the feature would be less "discoverable", and harder to document ..
>
>  I think .. a flag .. is a better developer UX.

I agree, a flag is more intuitive, but I could live with either, and I'm just waiting to hear which one André wants.

**Comment by indirect** [comment]
I think that a flag that is also enabled if the output is being piped makes sense. Anyone have ideas for the flag name? I don't think `--quiet` works because that already means silencing all output. `--minimal` makes me think it might apply to the command itself rather than the output. Maybe something like `--script-output`?

**Comment by segiddins** [comment]
I'm in favor or `porcelain` because that's what git uses.

**Comment by jaredbeck** [comment]
> .. --minimal makes me think it might apply to the command itself rather than the output. Maybe something like --script-output?

I like the use of the word "output" in `--script-output`, but it could be misinterpreted as "output which can be run as a script".

> I'm in favor [of] porcelain because that's what git uses.

It looks like [`npm` also uses `--porcelain`][1] and its synonym, `--parseable`. I like `--parseable` better than `--porcelain`.

`--parseable` is my current favorite, but it's up to you, André.

[1]: https://docs.npmjs.com/misc/config

**Comment by indirect** [comment]
I like `--parseable` too, and I'm happy to also have an alias `--porcelain`.

**Comment by RochesterinNYC** [comment]
Should have a PR ready for this by weekend.

Output will look like this though:
```
activesupport (newest 3.0, installed 2.3.5, requested = 2.3.5)
foo (newest 1.0)
weakling (newest 0.2, installed 0.0.3, requested ~> 0.0.1)
zebra (newest 1.0 d1549e2, installed 1.0 b2b6acc)
```

I'm not sure how to get the output like:
```
  * newrelic_rpm (3.12.0.288 > 3.11.2.286)
  * rack (1.6.1 > 1.6.0)
  * scrypt (2.0.0 > 1.2.1)
  * slop (4.1.0 > 3.6.0)
  * sprockets-rails (2.3.0 > 2.2.4)
  * tilt (2.0.1 > 1.4.1)
```

with the `>` sign though. Running `bundle outdated` with v1.11.2 does not produce this output?

**Comment by jaredbeck** [comment]
> Output will look like this ..

That's fine by me. The `"(%s > %s)"` format is soooo last year :p

**Comment by RochesterinNYC** [comment]
Closed by #4280

**Comment by jaredbeck** [comment]
> Closed by bundler/bundler#4280

Thanks James, I look forward to trying it out!

Oh, by the way (maybe I should have mentioned this earlier) my use case for this is automating `bundle update`, which is something I do once or twice a day.  I like to have one commit per gem update (to aid in bisect debugging) and sometimes I do things like: only update patch levels, or only update minor levels. This gets boring, so I need [tools][1] and `--parseable` output will help a lot.

Thanks again!

[1]: https://github.com/jaredbeck/shellconf/blob/master/bin/ruby/bunup.rb

**Comment by indirect** [comment]
We've also added `update --minor` and `update --tiny`, and feedback on them would be welcome.

**Comment by jaredbeck** [comment]
> We've also added update --minor and update --tiny, and feedback on them would be welcome.

That's awesome! It hasn't been released yet though?

```
bundle update --tiny
Unknown switches '--tiny'
bundle -v
Bundler version 1.11.2
```

I look forward to trying it out!

**Comment by RochesterinNYC** [comment]
It's been released in the `v1.12.0.pre.1` release.

https://github.com/bundler/bundler/releases

**Comment by indirect** [comment]
You can install the prerelease by running `gem install bundler --pre`! :)

**Comment by jaredbeck** [comment]
Still getting "unknown switch" with 1.12.0.pre.1

```
bundle -v
Bundler version 1.12.0.pre.1
bundle update --tiny
Unknown switches '--tiny'
bundle update --minor
Unknown switches '--minor'
```

Do you want a separate issue for this?

**Comment by RochesterinNYC** [comment]
Verified that this is the case with `1.12.0.pre.1` for me as well. I also don't see any mention of `minor` in relation to `bundle update` in the `cli.rb` file (https://github.com/bundler/bundler/blob/master/lib/bundler/cli.rb#L176-L201) and don't see any mention of the word 'tiny' at all in the codebase (https://github.com/bundler/bundler/search?q=tiny&type=Code&utf8=%E2%9C%93)? 

Which PR(s) were the `--tiny` and `--minor` flags introduced in?

**Comment by segiddins** [comment]
`bundle outdated --minor` works for me

**Comment by RochesterinNYC** [comment]
Are we talking about `bundle outdated --minor` or `bundle update --minor` ? 

`bundle outdated --minor` works for me but `bundle update --minor` does not. 

Both `bundle outdated --tiny` and `bundle update --tiny` does not.

Maybe @indirect meant `bundle outdated --minor` in his original comment rather than `bundle update --minor`? Not sure about the situation with the `--tiny` flag, though.

**Comment by indirect** [comment]
Maybe I'm confusing `outdated` and thinking that we added it to update. It would be pretty great to have `outdated` and `update` share those options.

**Comment by RochesterinNYC** [comment]
Sure, what would the `--tiny` flag do?

**Comment by indirect** [comment]
the `--tiny` (or perhaps `--bugfix`?) option would limit the `uodate` and `outdated` commands to only find updates to the third version number segment, similar to how `--minor` limits versions to changes in the second version number segment

**Comment by RochesterinNYC** [comment]
@indirect looking more into it, it doesn't seem that the `--minor` flag for `bundle outdated` limits versions to changes __only__ in the second version number segment but rather changes in __at least__ that number segment.

The description of the `--minor` flag: `"Only list at least minor newer versions"`

So if the latest version of a gem was `v1.2.5`, then `bundle outdated --minor` would report updates for a Gemfile with `v0.5.5` of that gem (`5 > 2` but the `at least minor newer version constraint` applies) and `v1.1.5` but not `v1.2.4`.

Hence, this `--tiny` flag has a kind of new behavior and should actually be called something along the lines of `--only-patch` maybe? Since it would exhibit the following behavior:
If the latest version of a gem was `v1.2.5`, then `bundle outdated --only-patch` would report updates for a Gemfile with `v1.2.4` of that gem but not `v1.1.5` or `v0.2.5`.

This is because if we wanted the flag to have the behavior of `"Only list at least patch newer versions"`, this would be the default behavior of `bundle outdated`, I believe. Thoughts?

**Comment by indirect** [comment]
@RochesterinNYC hmmmmmm. my understanding was that `--minor` excluded major version changes (e.g. 0.x to 1.x or 1.x to 2.x). My idea of `--tiny` was based on that, and I imagined it would show or update 1.5.3 to 1.5.8 but not 1.6.0.

Maybe it would be better to have a single `update` command with a `--dry-run` option so that the `outdated` and `update` commands can't get out of sync 😝

**Comment by RochesterinNYC** [comment]
Hm, okay, looking at the code and after playing around a bit, I don't believe this is the case. The code constructs strings of the major and minor version portions and ends up doing comparisons between them (ex. for `--minor`: `"2.1" <= "1.131242"`).

This is the following code for the `--minor` flag via `lib/bundler/cli/outdated.rb`:
```ruby
if options[:minor]
  current_minor = current_spec.version.segments[0, 2].compact.join(".")
  active_minor = active_spec.version.segments[0, 2].compact.join(".")
  # no update if newest major.minor is not > Gemfile major.minor
  active_spec = nil unless active_minor > current_minor
end
```

So if the current version for a gem is `v1.14.13` and the latest version is `v2.1.3`, the `current_minor` is `"1.14"` and the `active_minor` is `"2.1"`, the comparison is `"2.1" <= "1.14"` so there is an update reported. The integration spec for `bundle outdated --minor` reflects this as well. 

Do we want to change the behavior for `--minor` and `--major` to what you're thinking? If I implement `--tiny` according the current `--minor` and `--major`, I think it'd be the same as what `bundle outdated` currently does by default... (i.e. comparing the whole version `"2.1.3" <= "1.14.13"`).

And YES, that'd be so much cleaner...I'd love to merge the underlying logic for both since they seem so similar in functionality. If you're serious, it'd be great to work on that.

**Comment by chrismo** [comment]
@jaredbeck - ran across this issue doing some research tonight, i have a recent plugin that might help you in regard to your comments: "I do things like: only update patch levels, or only update minor levels. This gets boring, so I need tools and --parseable output will help a lot." -- [bundler-patch](https://github.com/livingsocial/bundler-patch)
